Extract the common code (#701)
* extract duplicate code into common module:
1. litentry/litmus/moonbase/rococo lib.rs:
* variables: RuntimeBlockLength BlockHashCount

2. litentry/litmus/moonbase/rococo transaction_payment.rs:
* variables: TargetBlockFullness AdjustmentVariable MinimumMultiplier SlowAdjustingFeeUpdate

* move litentry/litmus/moonbase/rococo transaction_payment.rs to runtime_common/lib.rs:

* move litentry/litmus/moonbase/rococo variables/constants to the common module:
* RuntimeBlockWeights
* AVERAGE_ON_INITIALIZE_RATIO
* MAXIMUM_BLOCK_WEIGHT

* Optimize imports

* refactor xcm_config.rs:
* move a part of the code in the litmus/moonbase/rococo xcm_config.rs(struct: FirstAssetTrader XcmFeesToAccount MultiNativeAsset) to runtime_common module:

* refactor xcm_config.rs

extract different types of converters to common_module:
1. CurrencyId <--->MultiLocation
2. AccountId --> MultiLocation
3. AssetId  <---> MultiLocation

* use LF instead of CRLF

* refactor test code

1. move litmus test code to common module
2. rococo/moonbase runtime  adjust the new common module

* fix test relay chain Config

* fix litmus test code

* extract common type into a new trait

* extract common type into a new trait

* rename RuntimeConfig to ParaRuntimeRequirements

* adjust rococo test code

* adjust moonbase test code

* fix compilation errors

* format code

* adjust the test code of litentry

* format code

* give execution permission to script files

* fix clippy error:

1. optimize code
2. remove useless code/mod/import

* correct the error configuration

1. ExtrinsicFilter Mode: Normal -> Test

* format code

* give execution permission

* Update runtime/common/src/xcm_impl.rs

Co-authored-by: Kai <7630809+Kailai-Wang@users.noreply.github.com>

* remove useless code

* remove comments

* format code

* move `ParaRuntimeRequirements` `BaseRuntimeRequirements` to lib.rs

* extract common tests into macros

Co-authored-by: Ming <btxhuman@gmail.com>
Co-authored-by: Kai <7630809+Kailai-Wang@users.noreply.github.com>